In [6]:
##Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays. 
import numpy as np
arr=np.array([[4,3,2],[10,1,0],[5,8,24]])
print("original array:\n",arr)

original array:
 [[ 4  3  2]
 [10  1  0]
 [ 5  8 24]]


In [19]:
print("indexing:\n")
print("element at[0,1]=",arr[0,1])
print("element at[-1,-1]=",arr[-1,-1])

indexing:

element at[0,1]= 3
element at[-1,-1]= 24


In [18]:
print("slicing:\n")
print("row:\n",arr[:1,:])
print("column:\n",arr[:,2:])

slicing:

row:
 [[4 3 2]]
column:
 [[ 2]
 [ 0]
 [24]]


In [25]:
a=np.arange(1,13)
reshaped=a.reshape(3,4)
print("reshaped array:\n")
print(reshaped)

reshaped array:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
b=np.array([20,30,40])
print("broadcasting:\n",arr+b)

broadcasting:
 [[24 33 42]
 [30 31 40]
 [25 38 64]]


In [28]:
A=np.array([[1,2,1],[2,2,3]])
B=np.array([3,4,5])
print("array A:\n",A)
print("array B:\n",B)


array A:
 [[1 2 1]
 [2 2 3]]
array B:
 [3 4 5]


In [38]:
add=np.add(A,B)
print("addition:\n",add)
sub=np.subtract(B,A)
print("subtraction:\n",sub)
multi=np.multiply(A,B)
print("multiplication:\n",multi)
div=np.divide(A,B)
print("dicision:\n",div)
power=np.power(A,B)
print("power:\n",power)

addition:
 [[4 6 6]
 [5 6 8]]
subtraction:
 [[2 2 4]
 [1 2 2]]
multiplication:
 [[ 3  8  5]
 [ 6  8 15]]
dicision:
 [[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]
power:
 [[  1  16   1]
 [  8  16 243]]


In [33]:
sub=np.subtract(A,B)
print("subtraction:\n",sub)

subtraction:
 [[-2 -2 -4]
 [-1 -2 -2]]


In [34]:
sub=np.subtract(B,A)
print("subtraction:\n",sub)

subtraction:
 [[2 2 4]
 [1 2 2]]


In [35]:
multi=np.multiply(A,B)
print("multiplication:\n",multi)

multiplication:
 [[ 3  8  5]
 [ 6  8 15]]


In [36]:
div=np.divide(A,B)
print("dicision:\n",div)

dicision:
 [[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


In [37]:
power=np.power(A,B)
print("power:\n",power)

power:
 [[  1  16   1]
 [  8  16 243]]
